# Generated by Django 6.0.7 on 2026-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='heleket_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('heleket', 'Heleket')], max_length=20, null=True),
        ),
    ]
